# Tentative file to use GitHub Actions

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      - name: Run Backend Tests
        run: |
          cd backend
          npm test
      - name: Build Backend
        run: |
          cd backend
          npm run build

  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy:
    name: Deploy to Local Server
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no user@your-vm-ip << 'EOF'
            # Navigate to the application directory
            cd /path/to/your/app

            # Pull the latest changes from the main branch
            git pull origin main
            
            # Deploy backend
            cd backend
            npm install
            pm2 restart all  # Restart the backend service

            # Deploy frontend
            cd ../frontend
            npm install
            npm run build
            
            # Copy the build files to the Nginx web root
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            # Reload Nginx to serve the updated frontend
            sudo systemctl reload nginx
          EOF

